services:
  server:
    build: 
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  database:
    image: mongo
    restart: always
    ports: 
    - 27017:27017
    volumes:
      - nestjs-swagger-mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password123

volumes:
  nestjs-swagger-mongodb: